// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJuQxtqUhaztRGfNrsoaUgJeoANK84Jxk',
    appId: '1:1042055541120:web:03df525c085e60e4e39165',
    messagingSenderId: '1042055541120',
    projectId: 'dicoding-ditonton-7be37',
    authDomain: 'dicoding-ditonton-7be37.firebaseapp.com',
    storageBucket: 'dicoding-ditonton-7be37.firebasestorage.app',
    measurementId: 'G-H06BM5BZ89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsR6lESUDFFDIa3bCDHvUboMQmCJrd2zk',
    appId: '1:1042055541120:android:cecce9c6762a30c3e39165',
    messagingSenderId: '1042055541120',
    projectId: 'dicoding-ditonton-7be37',
    storageBucket: 'dicoding-ditonton-7be37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWPcAjwF6xY-oWBDGu3lZukjPJvtae54',
    appId: '1:1042055541120:ios:516c1ed95c15d3a0e39165',
    messagingSenderId: '1042055541120',
    projectId: 'dicoding-ditonton-7be37',
    storageBucket: 'dicoding-ditonton-7be37.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
